language: node_js
node_js:
  - '12'
branches:
  only:
    - develop
deploy:
  provider: heroku
  on:
    branch: master
  api_key:
    secure: bt0yKzvM1RSyoF4pfTj02AtAruYwrKaQlW9fAiwiSgteh1BRSWxbO98TFjg7k8KVDQ1Z11OYTb+vdHB0I5UTky3VLoInJJ8r5sqTdAcbUYsm975adbw0snjNugyLu6L3s6c11kbyRWIgcJ/JznylTSv0Vy4GFJgbOm1FJZK6oKUZwkyzoWqgPlMq3jkvpZFjpisMl4Gx9jTEGM0O2jo0vP536Yi2+pBagDgA5PeVBqqxBXGpamDiitJ6hoFkFd5CGxU+GLF2cOzGreYPy/swhqzOmJMByxfKdNHOJXVUw7RP7OTnflDIFVWgGE4ypNYaa6KJ7CzlDnFOQ23fng9QmlQ/HsyNHJnNcJt8eOIawParWUtTf3s31eCRADBGK5T8gV59zDS4mN1exfdPGoCxYUV2YG9UPMNz/nVuJvkDyoHHeZWaneG1aBjw9ahbeUkfBTtynYe7XZBQPawyVcjsCWUhuJj164krWSXLTk3+6ijInzG9NunwK8qsPOnR8ax+XHDdEWLCbe1nAM7UAAUH1Tsjfv49qbkx2WPXtGua6G7wv3QoInqhkiCjyLuuDBTOOUZmgMTkaq2wMfFykl5ABYZ7kkrgODn9fH1MUCa7LZga10BbX78OCEv0r3tB5qyNt8cNyxf05EOGfgA3y6DTKBKPwRy16hYggP6rze/yQK8=
  app: boxting-rest-api
notifications:
  email:
    on_failure: change
    on_success: change